name: "Setup Frontend"
description: "Sets up Node.js environment and installs NPM packages"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20"
  install-deps:
    description: "Whether to install dependencies"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4 # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      shell: bash
      if: inputs.install-deps == 'true'
      run: |
        cd frontend
        npm ci
