name: "Setup Backend"
description: "Sets up Python environment, installs system dependencies, and installs Python packages"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.12"
  install-deps:
    description: "Whether to install dependencies"
    required: false
    default: "true"
  install-dev-tools:
    description: "Whether to install development tools (ruff, mypy, pytest)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5 # v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: |
          backend/requirements.txt
          backend/pyproject.toml

    - name: Install system dependencies
      shell: bash
      if: inputs.install-deps == 'true'
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq libmagic1

    - name: Install Python dependencies
      shell: bash
      if: inputs.install-deps == 'true'
      run: |
        cd backend
        # Use pip with --prefer-binary for faster installation
        pip install --upgrade pip --prefer-binary
        pip install -r requirements.txt --prefer-binary

    - name: Install Development Tools
      shell: bash
      if: inputs.install-dev-tools == 'true'
      run: |
        pip install ruff mypy pytest pytest-cov pytest-xdist pytest-asyncio --prefer-binary
        pip install types-requests types-redis types-Pillow types-bleach --prefer-binary
